### ISSUE TITLE
Build failure on RHEL 7.4

### ISSUE THREAD

**Issue by popxunga** [bugzy/keepassxc-rpm-spec#7]
Hi ...
I'm trying to build latest (2.3.1) keepassxc version on RHEL 7.4 but it fails with the same error that can be seen here: https://copr-be.cloud.fedoraproject.org/results/bugzy/keepassxc/epel-7-x86_64/00725080-keepassxc/build.log.gz
I wonder how the latest (7 March 2018) centos7 package was successfully built.
Any help will be welcome.
Thanks.

**Comment by bugzy** [comment]
@popxunga the failure to build is due to the version of libgcrypt available on RHEL 7.4; you need a version of libgcrypt >=1.7 because the chcacha20 cypher, which is required for keepassxc >= 2.3.1, is unavailable in earlier versions. 
Sorry about the delayed response.

**Comment by popxunga** [comment]
Hi @bugzy  !
I'm aware of the libcrypt >= 1.7 requirement, but current libgcrypt version on RHEL 7.4 is 1.5.3. 
I'm not sure what's the current libgcrypt version on CentOS 7, but it should be the same, because CentOS 7 is based on RHEL 7. And this should be the reason why the libgcrypt16 package (also available from this repo) exists (because the libgcrypt package on CentOS 7 is an old version like in RHEL 7).
So my question is how did the CentOS 7 build in this repo succeed using the libgcrypt16 which doesn't include the CHACHA20 cypher either ? 
In the log above I see:
BUILDSTDERR: /builddir/build/BUILD/keepassxc-2.3.1/src/crypto/Crypto.cpp:98:31: error: 'GCRY_CIPHER_CHACHA20' was not declared in this scope
Thanks again for your support.

**Comment by bugzy** [comment]
@popxunga the build failed for CentOS ( see https://copr.fedorainfracloud.org/coprs/bugzy/keepassxc/build/725080/). 
It succeeded only for f26 and f27, and I suspect that the builds on f26 and f27 is what you are looking at.

**Comment by popxunga** [comment]
@bugzy ... sorry my bad ! 
You're correct. There's the src.rpm only. I guess I'm getting too old for this :-)
Anyway ... we would need a libgcrypt17 (or back port the modifications of libgcrypt 1.7 into the existing libgcrypt16) in order to make the CentOS build. Am I correct ?
Sorry once more and thanks.

**Comment by bugzy** [comment]
@popxunga You are right. I asked @hifi if he would be able to work on a libgcrypt 1.7 and he indicated that he does not use CentOS as a desktop OS anymore so he may not be able to do it, but if he gets a spot of time he may work on it.

**Comment by popxunga** [comment]
Thanks @bugzy ... 
No rush ... but I hope @hifi can help :-)

**Comment by bugzy** [comment]
@popxunga 
I was able to build libgcrypt 1.7 for CentOS 7 (see https://copr-be.cloud.fedoraproject.org/results/bugzy/keepassxc/epel-7-x86_64/00755093-libgcrypt17/)

The lastest version of keepassxc should now be available for CentOS 7 and RHEL at https://copr-be.cloud.fedoraproject.org/results/bugzy/keepassxc/epel-7-x86_64/00755097-keepassxc/ 

or just use the repo at https://copr.fedorainfracloud.org/coprs/bugzy/keepassxc/repo/epel-7/bugzy-keepassxc-epel-7.repo

**Comment by popxunga** [comment]
Hi ! Many thanks @bugzy !
Looks like I'll have to wait that Redhat updates libgpg-error package to
version 1.13 (currently they have version 1.12 on RHEL 7.5), as no i686
version of libgpg-error 1.13 is provided in your repo.This generates an
issue during the upgrade on multilib/arch systems like mine. I can only
upgrade libgpg-error from v1.12 to 1.13 version if I have both the i686 and
x64 versions of libgpg-error packages.
Kind regards.


A quarta, 16/05/2018, 17:33, bugzy <notifications@github.com> escreveu:
